# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AreUDone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AreUDone
  pod 'RealmSwift'

  target 'AreUDoneTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'KeychainFramework' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KeychainFramework

end

target 'NetworkFramework' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NetworkFramework

end
