version: "3"
services:
  mysql:
    image: mysql:5.7
    # volumes:
    #   - "./.mysql:/var/lib/mysql"
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: 
      - --default-authentication-plugin=mysql_native_password 
      - --character-set-server=utf8 
      - --collation-server=utf8_unicode_ci
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8888:8080