name: Server CI/CD on Branch 'develop/web'
on:
  push:
    branches: [ develop/web ]
  pull_request:
    branches: [ develop/web ]
defaults:
  run:
    shell: bash
    working-directory: ./server
jobs:
  test:
    env:
      MYSQL_DATABASE: areudonedb
      MYSQL_USER: areudone
      MYSQL_PASSWORD: 123123
      MYSQL_ROOT_PASSWORD: 123123
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x
      - run: npm install
      - run: npm run lint
      - run: npm run build
      - run: |
          touch .env
          touch .env.test
          echo NODE_ENV=test >> .env
          echo DATABASE_TYPE=mysql >> .env.test
          echo DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@localhost:3306/${MYSQL_DATABASE} >> .env.test
          echo DATABASE_DROP_SCHEMA=true >> .env.test
          echo DATABASE_SYNCHRONIZE=true >> .env.test
          echo JWT_SECRET=sjfklajslfjaslfjals >> .env.test
          echo OAUTH_NAVER_CLIENT_ID=vdEhOcPIbq3NUryKWnDh >> .env.test
          cat .env.test
      - run: npm run test
    services:
      db:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
          MYSQL_USER: ${{ env.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ env.MYSQL_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_ROOT_PASSWORD }}
  deploy:
    if: ${{ github.event_name == 'push' }}
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x
      - run: npm install
      - run: npm run build
      - name: Create environment files
        run: |
          touch .env
          touch .env.development
          echo NODE_ENV=development >> .env
          for env in $DEVELOP_SERVER_ENVIRONMENTS
          do
            echo $env >> .env.development
          done
        env:
          DEVELOP_SERVER_ENVIRONMENTS: ${{ secrets.DEVELOP_SERVER_ENVIRONMENTS }}
      - uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.DEVELOP_SERVER_HOST }}
          port: ${{ secrets.DEVELOP_SERVER_PORT }}
          username: ${{ secrets.DEVELOP_SERVER_USERNAME }}
          password: ${{ secrets.DEVELOP_SERVER_PASSWORD }}
          target: /home/${{ secrets.DEVELOP_SERVER_USERNAME }}
          source: ./server
          overwrite: true
      - uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.DEVELOP_SERVER_HOST }}
          port: ${{ secrets.DEVELOP_SERVER_PORT }}
          username: ${{ secrets.DEVELOP_SERVER_USERNAME }}
          password: ${{ secrets.DEVELOP_SERVER_PASSWORD }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ~/server
            pm2 reload ecosystem.config.js
